apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-build-push-run
spec:
  params:
  - name: repo-url
    value: https://github.com/V-vk-404/New-Budget-App.git
  - name: image-reference
    value: jarvis99/new-budget-app
  - name: image-tag
    value: v1.0.0
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  serviceAccountName: docker-service-account